"""
MEC (Mobile Edge Computing) manager.

- Task / request model
- M/M/1 queuing for bandwidth, compute, storage resources
- Computation offloading with configurable offload ratio δ ∈ [0,1]
"""

from __future__ import annotations
import numpy as np
from dataclasses import dataclass, field
from typing import List, Optional
from ..config import (
    TASK_DATA_SIZE, TASK_COMPUTE_CYCLES, TASK_RESULT_SIZE,
    CMOS_KAPPA, NOISE_PSD, SPEED_OF_LIGHT,
)

_EPS = 1e-30


@dataclass
class Task:
    """A computation request generated by an IoT device (buoy)."""
    task_id: int
    source_id: int
    data_size: float = TASK_DATA_SIZE            # bytes
    compute_cycles: float = TASK_COMPUTE_CYCLES  # CPU cycles
    result_size: float = TASK_RESULT_SIZE         # bytes
    offload_ratio: float = 0.0                    # δ ∈ [0,1]
    allocated_bw: float = 0.0
    allocated_comp: float = 0.0
    allocated_stor: float = 0.0
    mec_node_id: Optional[int] = None

    # ---- delay components -------------------------------------------------

    def transmission_delay(self, bandwidth: float, sinr_linear: float) -> float:
        """Shannon capacity based transmission delay."""
        capacity = bandwidth * np.log2(1.0 + sinr_linear)  # bits/s
        capacity = max(capacity, _EPS)
        return self.data_size * 8.0 / capacity  # seconds

    def computation_delay(self, compute_flops: float) -> float:
        compute_flops = max(compute_flops, _EPS)
        return self.compute_cycles / compute_flops

    @staticmethod
    def queuing_delay_mm1(arrival_rate: float, service_rate: float) -> float:
        """M/M/1 queue: W = 1/(μ - λ).  Returns ∞ if system is unstable."""
        if service_rate <= arrival_rate:
            return 1e6  # effectively infinite
        return 1.0 / (service_rate - arrival_rate)

    # ---- total delay ------------------------------------------------------

    def total_delay_no_offload(
        self,
        bw: float,
        sinr_linear: float,
        comp: float,
        arrival_rate: float,
        avg_data: float,
        avg_cycles: float,
        avg_stor: float,
        stor: float,
    ) -> float:
        """Total delay when δ=0: full offload to MEC (no local parallel path).

        T = T_tx + T_comp + W_bw + W_comp + W_stor
        """
        t_tx = self.transmission_delay(bw, sinr_linear)
        t_comp = self.computation_delay(comp)

        mu_bw = bw / max(avg_data * 8.0, _EPS)
        mu_comp = comp / max(avg_cycles, _EPS)
        mu_stor = stor / max(avg_stor, _EPS)

        w_bw = self.queuing_delay_mm1(arrival_rate, mu_bw)
        w_comp = self.queuing_delay_mm1(arrival_rate, mu_comp)
        w_stor = self.queuing_delay_mm1(arrival_rate, mu_stor)

        return t_tx + t_comp + w_bw + w_comp + w_stor

    def total_delay_with_offload(
        self,
        delta: float,
        local_comp: float,
        mec_comp: float,
        bw_up: float,
        bw_down: float,
        sinr_up: float,
        sinr_down: float,
        arrival_rate: float,
        avg_data: float,
        avg_cycles: float,
        avg_stor: float,
        mec_stor: float,
    ) -> float:
        """Total delay with partial offloading (ratio δ).

        Local path:  T_local = (1-δ)·C / f_local
        Offload path: T_off = T_upload + T_mec_comp + T_download + queuing
        T_total = max(T_local, T_offload)      (parallel)
        """
        t_local = (1.0 - delta) * self.compute_cycles / max(local_comp, _EPS)

        cap_up = bw_up * np.log2(1.0 + sinr_up)
        cap_down = bw_down * np.log2(1.0 + sinr_down)
        t_upload = delta * self.data_size * 8.0 / max(cap_up, _EPS)
        t_mec_comp = delta * self.compute_cycles / max(mec_comp, _EPS)
        t_download = self.result_size * 8.0 / max(cap_down, _EPS)

        mu_bw = bw_up / max(avg_data * 8.0, _EPS)
        mu_comp = mec_comp / max(avg_cycles, _EPS)
        mu_stor = mec_stor / max(avg_stor, _EPS)
        w_bw = self.queuing_delay_mm1(arrival_rate, mu_bw)
        w_comp = self.queuing_delay_mm1(arrival_rate, mu_comp)
        w_stor = self.queuing_delay_mm1(arrival_rate, mu_stor)

        t_offload = t_upload + t_mec_comp + t_download + w_bw + w_comp + w_stor
        return max(t_local, t_offload)

    # ---- storage energy ----------------------------------------------------

    @staticmethod
    def storage_energy(data_size: float, stor_power_per_byte: float = 1e-9) -> float:
        """Energy for reading/writing data to storage.
        E_stor = P_stor_per_byte × data_size
        Typical NAND flash: ~1 nJ/byte.
        """
        return stor_power_per_byte * data_size

    # ---- energy -----------------------------------------------------------

    def energy_no_offload(self, comp: float, tx_power: float,
                          bw: float, sinr_linear: float) -> float:
        """E = κ·f³·T_comp + P_tx·T_tx + E_stor  (MEC compute + uplink tx + storage)."""
        t_comp = self.computation_delay(comp)
        e_comp = CMOS_KAPPA * (comp ** 3) * t_comp
        t_tx = self.transmission_delay(bw, sinr_linear)
        e_tx = tx_power * t_tx
        e_stor = self.storage_energy(self.data_size + self.result_size)
        return e_comp + e_tx + e_stor

    def energy_with_offload(
        self,
        delta: float,
        local_comp: float,
        tx_power: float,
        rx_power: float,
        bw_up: float,
        bw_down: float,
        sinr_up: float,
        sinr_down: float,
    ) -> float:
        """E = κ·f³·T_local + P_tx·T_upload + P_rx·T_download + E_stor."""
        t_local = (1.0 - delta) * self.compute_cycles / max(local_comp, _EPS)
        e_local = CMOS_KAPPA * (local_comp ** 3) * t_local

        cap_up = bw_up * np.log2(1.0 + sinr_up)
        t_upload = delta * self.data_size * 8.0 / max(cap_up, _EPS)
        e_tx = tx_power * t_upload

        cap_down = bw_down * np.log2(1.0 + sinr_down)
        t_download = self.result_size * 8.0 / max(cap_down, _EPS)
        e_rx = rx_power * t_download

        e_stor = self.storage_energy(self.data_size + self.result_size)

        return e_local + e_tx + e_rx + e_stor


class MECManager:
    """Manages MEC task generation, offloading decisions, and resource queuing."""

    _task_counter: int = 0

    def __init__(self):
        self.pending_tasks: List[Task] = []
        self.completed_tasks: List[Task] = []

    def generate_task(self, source_id: int, data_size: float = TASK_DATA_SIZE,
                      compute_cycles: float = TASK_COMPUTE_CYCLES) -> Task:
        MECManager._task_counter += 1
        t = Task(
            task_id=MECManager._task_counter,
            source_id=source_id,
            data_size=data_size,
            compute_cycles=compute_cycles,
        )
        self.pending_tasks.append(t)
        return t

    def reset(self):
        self.pending_tasks.clear()
        self.completed_tasks.clear()
        MECManager._task_counter = 0
